apply plugin: 'com.android.application'

android {

    namespace 'com.naman14.tandroidlame'
    compileSdk 36
    ndkVersion "28.2.13676358"

    defaultConfig {
        applicationId "com.naman14.tandroidlame"
        minSdkVersion 21
        targetSdkVersion 36
        versionCode 3
        versionName "2.0.1"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles.add(file("proguard-rules.pro"))
        }
    }

    externalNativeBuild {
        ndkBuild {
            path '../androidlame/src/main/jni/Android.mk'
        }
    }
}


dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support:recyclerview-v7:26.1.0'
    implementation project(':androidlame')

    testImplementation 'junit:junit:4.13.2'
}